=== kunzhao3/pricing/web/src/main/resources/excel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- 限定为字符串类型 -->
    <xs:simpleType name="stringType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <!-- 限定为整数类型 -->
    <xs:simpleType name="integerType">
        <xs:restriction base="xs:integer"/>
    </xs:simpleType>

    <xs:element name="parses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="parse" type="parseType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="parseType">
        <xs:sequence>
            <xs:element name="columns" type="columnsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="stringType" use="required"/>
        <xs:attribute name="name" type="stringType" use="required"/>
        <xs:attribute name="filename" type="stringType"/>
        <xs:attribute name="filetype" type="stringType"/>
        <xs:attribute name="classname" type="stringType" use="required"/>
    </xs:complexType>

    <xs:complexType name="columnsType">
        <xs:sequence>
            <xs:element name="column" type="columnType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="columnType">
        <xs:attribute name="cidx" type="integerType" use="required"/>
        <xs:attribute name="cname" type="stringType" use="required"/>
        <xs:attribute name="pname" type="stringType" use="required"/>
        <xs:attribute name="type" type="stringType"/>
        <xs:attribute name="cformat" type="stringType"/>
        <xs:attribute name="handler" type="stringType"/>
    </xs:complexType>
</xs:schema>

=== kunzhao3/pricing/web/src/main/resources/excelWrite.xml
<?xml version="1.0" encoding="UTF-8"?>
<parses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="excel.xsd">

	<parse id="PricingFeeBean" name="定价费项" filename="" filetype="" classname="com.parses.server.bean.PricingFeeBean">
		<columns>
			<column cidx="0" cname="定价类型" pname="pricingType" type="" cformat="" handler=""/>
			<column cidx="1" cname="定价编号" pname="pricingNo" type="" cformat="" handler=""/>
			<column cidx="2" cname="定价镜像编号" pname="pricingMirrorNo" type="" cformat="" handler=""/>
			<column cidx="3" cname="费用代码" pname="feeCode" type="" cformat="" handler=""/>
			<column cidx="4" cname="费用名称" pname="feeName" type="" cformat="" handler=""/>
			<column cidx="5" cname="费用描述" pname="feeDescription" type="" cformat="" handler=""/>
			<column cidx="6" cname="计算周期" pname="calcPeriod" type="" cformat="" handler=""/>
			<column cidx="7" cname="公式类型" pname="formulaType" type="" cformat="" handler=""/>
		</columns>
	</parse>

</parses>

=== kunzhao3/pricing/web/src/main/resources/excelRead.xml
<?xml version="1.0" encoding="UTF-8"?>
<parses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="excel.xsd">
	<parse id="ProductPricingBean" name="产品定价" filename="" filetype="" classname="com.parses.server.bean.ProductPricingBean">
		<columns>
			<column cidx="0" cname="产品编码" pname="productCode" type="" cformat="" handler=""/>
			<column cidx="1" cname="期次" pname="totalStage" type="" cformat="" handler=""/>
			<column cidx="2" cname="等级" pname="rankLevel" type="" cformat="" handler=""/>
			<column cidx="3" cname="标签" pname="consumerLabel" type="" cformat="" handler=""/>
			<column cidx="4" cname="年利率" pname="yearRate" type="" cformat="" handler=""/>
			<column cidx="5" cname="月综合利率" pname="aprMonthRate" type="" cformat="" handler=""/>
		</columns>
	</parse>

	<parse id="ExlFeeParamBean" name="定价费项属性" filename="" filetype="" classname="com.parses.util.bean.ExlFeeParamBean">
		<columns>
			<column cidx="0" cname="总期数" pname="totalStage" type="" cformat="" handler=""/>
			<column cidx="1" cname="风险等级" pname="rankLevel" type="" cformat="" handler=""/>
			<column cidx="2" cname="用户标签" pname="consumerLabel" type="" cformat="" handler=""/>
			<column cidx="3" cname="费用名称" pname="feeName" type="" cformat="" handler=""/>
			<column cidx="4" cname="费用代码" pname="feeCode" type="" cformat="" handler=""/>
			<column cidx="5" cname="年利率" pname="yearRate" type="" cformat="" handler=""/>
			<column cidx="6" cname="提前结清日利率" pname="preSettleDayRate" type="" cformat="" handler=""/>
			<column cidx="7" cname="利率" pname="baseRate" type="" cformat="" handler=""/>
			<column cidx="8" cname="年天数" pname="yearDays" type="" cformat="" handler=""/>
			<column cidx="9" cname="罚息/逾期违约金计算方式" pname="baseAmountType" type="" cformat="" handler=""/>
			<column cidx="10" cname="月综合利率" pname="complexMonthRate" type="" cformat="" handler=""/>
			<column cidx="11" cname="资方和对资担保公司IRR" pname="capitalAndUndertakeCapitalGuaranteeYearIRR" type="" cformat="" handler=""/>
			<column cidx="12" cname="结算利率" pname="settlementRate" type="" cformat="" handler=""/>
			<column cidx="13" cname="浮动利率" pname="floatingRate" type="" cformat="" handler=""/>
		</columns>
	</parse>

	<parse id="ElementDataBean" name="要素" filename="" filetype="" classname="com.parses.server.bean.ElementDataBean">
		<columns>
			<column cidx="1" cname="要素代码" pname="elementCode" type="" cformat="" handler=""/>
			<column cidx="2" cname="要素代码数据" pname="elementData" type="" cformat="" handler=""/>
		</columns>
	</parse>

</parses>
